-- Mapa Leads — execute uma vez no SQL Editor do seu projeto Supabase.
create extension if not exists pgcrypto;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references auth.users(id) on delete set null,
  business_key text not null,
  name text not null,
  city text,
  state text,
  address text,
  phone text,
  website text,
  rating numeric(2,1) check (rating is null or (rating >= 0 and rating <= 5)),
  reviews integer check (reviews is null or reviews >= 0),
  category text,
  niche text not null default 'other' check (niche in ('aesthetics','real_estate','health','beauty','food','services','retail','other')),
  maps_url text,
  place_id text,
  instagram text,
  email text,
  status text not null default 'new' check (status in ('new','contacted','replied','followup','discarded')),
  notes text not null default '',
  favorite boolean not null default false,
  follow_up_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_key)
);

create table if not exists public.lead_events (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete set null,
  company_id uuid not null references public.companies(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.import_batches (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete set null,
  filename text not null,
  source_rows integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.companies add column if not exists niche text not null default 'other';
alter table public.companies alter column owner_id drop not null;
alter table public.lead_events alter column owner_id drop not null;
alter table public.import_batches alter column owner_id drop not null;
create unique index if not exists companies_business_key_unique on public.companies(business_key);

create index if not exists companies_owner_status_idx on public.companies(owner_id, status);
create index if not exists companies_owner_follow_up_idx on public.companies(owner_id, follow_up_at);
create index if not exists companies_owner_city_idx on public.companies(owner_id, city);
create index if not exists companies_owner_niche_idx on public.companies(owner_id, niche);
create index if not exists lead_events_company_idx on public.lead_events(company_id, created_at desc);
create index if not exists import_batches_owner_idx on public.import_batches(owner_id, created_at desc);

alter table public.companies enable row level security;
alter table public.lead_events enable row level security;
alter table public.import_batches enable row level security;

drop policy if exists "companies_owner_all" on public.companies;
drop policy if exists "companies_public_all" on public.companies;
create policy "companies_public_all" on public.companies for all to anon, authenticated using (true) with check (true);
drop policy if exists "lead_events_owner_all" on public.lead_events;
drop policy if exists "lead_events_public_all" on public.lead_events;
create policy "lead_events_public_all" on public.lead_events for all to anon, authenticated using (true) with check (true);
drop policy if exists "import_batches_owner_all" on public.import_batches;
drop policy if exists "import_batches_public_all" on public.import_batches;
create policy "import_batches_public_all" on public.import_batches for all to anon, authenticated using (true) with check (true);


grant select, insert, update, delete on public.companies to anon;
grant select, insert, update, delete on public.lead_events to anon;
grant select, insert, update, delete on public.import_batches to anon;
grant select, insert, update, delete on public.companies to authenticated;
grant select, insert, update, delete on public.lead_events to authenticated;
grant select, insert, update, delete on public.import_batches to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant usage, select on all sequences in schema public to anon;
